JSWASI_SRC_REV := f920e1099017097d57397ff20226d689636d6ffb
JSWASI_SRC_URL := https://github.com/antmicro/jswasi/archive/$(JSWASI_SRC_REV).zip
JSWASI_SRC_ZIP := $(BUILD_DIR)/$(JSWASI_SRC_REV).zip
JSWASI_SRC_DIR := $(BUILD_DIR)/jswasi-$(JSWASI_SRC_REV)

JSWASI_DIST_DIR := $(JSWASI_SRC_DIR)/dist

$(JSWASI_SRC_ZIP): | $(BUILD_DIR)
	@wget -qO $(JSWASI_SRC_ZIP) $(JSWASI_SRC_URL)

$(JSWASI_SRC_DIR): $(JSWASI_SRC_ZIP) | $(BUILD_DIR)
	@unzip -od $(BUILD_DIR) $(JSWASI_SRC_ZIP)

.PHONY: $(JSWASI_DIST_DIR)
$(JSWASI_DIST_DIR): $(JSWASI_SRC_DIR)
	@cd $(JSWASI_SRC_DIR) && \
	make embed

.PHONY: JSWASI
JSWASI: $(JSWASI_DIST_DIR) | $(DIST_DIR)
	@cp -r $(JSWASI_DIST_DIR)/* $(DIST_DIR)
